### ISSUE TITLE
Null Pointer Error reading prices

### ISSUE THREAD

**Issue by capnkirok** [capnkirok/Voxels#20]
From DerpSquad1O1:

Need error trapping around Null items....

java.lang.NullPointerException: Rendering screen
at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
at com.voxels.io.PriceReader.main(PriceReader.java:91)
at com.voxels.events.TradeTooltips.itemTooltip(TradeTooltips.java:111)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_747_TradeTooltips_itemTooltip_ItemTooltipEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)

**Comment by capnkirok** [comment]
Added error trapping on 1.7.10 and 1.10 for both PriceReader and PriceGaps file generation
