### ISSUE TITLE
extreme lag when opening crafting table.

### ISSUE THREAD

**Issue by Jakalth** [capnkirok/Voxels#33]
For some reason I'm getting extreme lag when I open any crafting table.  The lag drops tick rate from the normal 40 down to ~1 while in the crafting screen.  I'm using Voxels in a modpack.  When I disable voxels, the rest of the modpack runs perfectly smooth.  Did a fresh install, and using latest forge for 1.10.2

In the log file, which the smallest one I have is 5.8mb and the largest was 2.44gb, It's filling the majority of the log with the same error code.  This is the repeated error...

[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: com.google.gson.stream.MalformedJsonException: Expected name at line 1577 column 2
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.voxels.io.PriceReader.main2(PriceReader.java:167)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.voxels.io.PriceReader.main(PriceReader.java:122)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.voxels.events.TradeTooltips.itemTooltip(TradeTooltips.java:109)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_567_TradeTooltips_itemTooltip_ItemTooltipEvent.invoke(.dynamic)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:265)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:794)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mcp.mobius.waila.overlay.DisplayUtil.itemDisplayNameMultiline(DisplayUtil.java:150)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mcp.mobius.waila.overlay.DisplayUtil.itemDisplayNameShort(DisplayUtil.java:171)
[15:42:04] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mcp.mobius.waila.handlers.HUDHandlerBlocks.getWailaHead(HUDHandlerBlocks.java:38)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:107)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:87)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_458_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:42:05] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Jakalth** [comment]
well, just on a hunch, I removed waila and its 2 companion mods and the crafting lag went away.  BUT, still get a repeated error for voxels, although not spammed as badly.  Now it states the following:

[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: com.google.gson.stream.MalformedJsonException: Expected name at line 1577 column 2
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.voxels.io.PriceReader.main2(PriceReader.java:167)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.voxels.io.PriceReader.main(PriceReader.java:122)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at com.voxels.events.TradeTooltips.itemTooltip(TradeTooltips.java:109)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_557_TradeTooltips_itemTooltip_ItemTooltipEvent.invoke(.dynamic)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:265)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:794)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:43)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.getTooltip(ItemStackRenderer.java:21)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.gui.ingredients.GuiIngredientFast.getTooltip(GuiIngredientFast.java:287)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.gui.ingredients.GuiIngredientFast.drawTooltip(GuiIngredientFast.java:273)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.gui.ingredients.GuiIngredientFast.drawTooltip(GuiIngredientFast.java:266)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.gui.ItemListOverlayInternal.drawTooltips(ItemListOverlayInternal.java:346)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at mezz.jei.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:108)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_626_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:383)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:32:39] [Client thread/INFO] [STDERR/]: [com.voxels.io.PriceReader:main2:185]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by capnkirok** [comment]
Yes, there's a special tooltip handler that can conflict with other tooltip mods and it just slows everything down while it's trying to figure out priorities..... I can add exceptions, but have only figured out to do it one at a time... what are the two companion mods from WAILA you are using and I will add them in.

**Comment by Jakalth** [comment]
Waila, Waila Harvestability, and Wawla.  Those three were the main conflicts.

The second issue though seems to be something with JEI.  Possibly due to having Just Enough Resources installed as well.

**Comment by capnkirok** [comment]
You know, I just started look at this one as a I wrapped up a few bugs in one update. I installed all of these mods, and even added mods with tons of items, and didn't see an issue.

Then I looked at the error again... it looks like you've got a formatting issue with the Prices.JSON file... like it's missing a quote, or it's using a curly quote somewhere, or the final bracket is missing etc. That's the only way you'd get a MalformedJsonException: Expected name at line 1577 column 2. Open up the JSON and see if you can find it at that line.

If this is printing to your console 5 times/second that's going to slow the whole thing down. Really sorry I didn't look at this closer, earlier.
